project:
  type: website
  output-dir: _site
  resources:
    - bookmarks

website:
  title: "Josh Day"
  site-url: https://joshday.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/joshday
      - icon: linkedin
        href: https://www.linkedin.com/in/joshday/

format:
  html:
    theme: cosmo
    css: styles.css
